version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v3.1.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    links:
      - clamav-prometheus-exporter:clamav-prometheus-exporter

  clamav-prometheus-exporter:
    image: sysadminliip/clamav-prometheus-exporter:latest
    command:
      - '--clamav-address=clamav'
    ports:
      - 9810:9810
    links:
      - clamav:clamav
    depends_on:
      clamav:
        condition: service_healthy

  clamav:
    image: mkodockx/docker-clamav:alpine
    ports:
      - 3310:3310
    healthcheck:
      test: [ "CMD", "./check.sh" ]
      interval: 60s
      retries: 3
      start_period: 120s
    volumes:
      - clamav-dir:/var/lib/clamav

volumes:
  clamav-dir: